### PR TITLE
chore: update go-redis import path

### PR DESCRIPTION
**Pull request by vmihailenco**
The repo has been moved to the official Redis org on GitHub so the import path must be updated.

### CODE REVIEW

**Comment by vmihailenco** [comment]
@dim gentle ping

**Comment by dim** [comment]
@vmihailenco thanks!

**Comment by khasanovbi** [comment]
Hi @dim, could you please bump library version?

**Comment by dim** [comment]
On it https://github.com/bsm/redislock/pull/57

**Pull request merged**
